name: recipe_app
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 3.8.2+9

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.2
  cupertino_icons: ^1.0.5
  file_picker: ^5.2.2
  firebase_auth: ^4.1.0
  firebase_core: ^2.1.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.0.6+4
  flutter_tts: ^3.5.3
  flutter_vector_icons: ^2.0.0
  get: ^4.6.5
  google_fonts: ^3.0.1
  google_mobile_ads: ^1.2.0
  google_sign_in: ^5.4.2
  html: ^0.15.1
  http: ^0.13.5
  image_picker: ^0.8.6
  intl: ^0.17.0
  logger: ^1.1.0
  mobx: ^2.1.1
  nb_utils: ^4.6.23
  numberpicker: ^2.1.1
  path_provider: ^2.0.11
  percent_indicator: ^4.2.2
  photo_view: ^0.14.0
  share: ^2.0.4
  share_plus: ^6.2.0
  sqflite: ^2.2.0+3
  step_progress_indicator: ^1.0.2
  the_apple_sign_in: ^1.1.1
  url_launcher: ^6.1.6

dev_dependencies:
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.7+3

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/flag/
