name: recipe_app
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 3.6.0+5

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.4
  firebase_auth: ^3.3.6
  firebase_core: ^1.12.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.0.4
  flutter_tts: ^3.3.3
  flutter_vector_icons: ^1.0.0
  get: ^4.6.1
  google_fonts: 2.2.0
  google_mobile_ads: ^1.0.1
  google_sign_in: ^5.2.3
  html: ^0.15.0
  http: ^0.13.4
  image_picker: ^0.8.4+6
  intl: ^0.17.0
  logger: ^1.1.0
  mobx: ^2.0.6+1
  native_admob_flutter: ^1.5.0
  nb_utils: ^4.4.11
  numberpicker: ^2.1.1
  package_info_plus: ^1.3.0
  path_provider: ^2.0.8
  percent_indicator: ^4.0.0
  photo_view: ^0.13.0
  share: ^2.0.4
  share_plus: ^3.0.4
  sqflite: ^2.0.2
  step_progress_indicator: ^1.0.2
  the_apple_sign_in: ^1.1.1
  url_launcher: ^6.0.18

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.5+2

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/flag/
